<?php

/*
 * This file is part of the TYPO3 project.
 *
 * @author Frank Berger <fberger@sudhaus7.de>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

namespace SUDHAUS7\Sudhaus7Wizard\Tests\Unit;

use SUDHAUS7\Sudhaus7Wizard\CreateProcess;
use TYPO3\CMS\Core\EventDispatcher\EventDispatcher;
use TYPO3\TestingFramework\Core\Unit\UnitTestCase;

class TCAFieldActiveForThisRecordTest extends UnitTestCase
{
    protected CreateProcess $create_process;
    protected $record = [
        'uid' => 1,
        'pid' => 1,
        'CType' => 'text',
        'header' => 'header',
        'header_link' => 'header_link',
        'header_layout' => 1,
        'bodytext' => '<p>bodytext</p>',

    ];
    protected $tca = [
        'tt_content' => [
            'ctrl' => [
                'type' => 'CType',
            ],
            'columns' => [
                'header' => [
                    'config' => [
                        'max' => 255,
                        'size' => 50,
                        'type' => 'input',
                    ],
                ],
                'header_link' => [
                    'config' => [
                        'max' => 255,
                        'size' => 50,
                        'type' => 'input',
                    ],
                ],
                'bodytext' => [
                    'config' => [
                        'type' => 'text',
                    ],
                ],
                'image' => [
                    'config' => [
                        'max' => 255,
                        'size' => 50,
                        'type' => 'input',
                    ],
                ],
                'header_layout' => [
                    'config' => [
                        'default' => 0,
                        'items' => [
                            ['label' => 'title 1', 'value' => 0],
                            ['label' => 'title 2', 'value' => 1],
                        ],

                        'renderType' => 'selectSingle',
                        'type' => 'select',
                    ],
                ],
            ],
            'palettes' => [
                'header' => [
                    'showitem' => 'header,header_layout,--linebreak--,header_link',
                ],
            ],
            'types' => [
                'text' => [
                    'columnsOverrides' => ['bodytext' => ['config' => ['enableRichtext' => 1]]],
                    'showitem' => '--div--;Allgemein,--palette--;;header,bodytext',
                ],
            ],
        ],
    ];
    protected function setUp(): void
    {
        $eventDispatcher = $this->createMock(EventDispatcher::class);
        $this->create_process = new CreateProcess($eventDispatcher);
        $GLOBALS['TCA']['tt_content'] = $this->tca['tt_content'];
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function isBodytextEnabledInThisRecord(): void
    {
        self::assertTrue($this->create_process->isTCAFieldActiveForThisRecord('tt_content', 'bodytext', $this->record));
    }
    /**
     * @test
     */
    public function isHeaderEnabledInThisRecord(): void
    {
        self::assertTrue($this->create_process->isTCAFieldActiveForThisRecord('tt_content', 'header', $this->record));
    }
    /**
     * @test
     */
    public function isHeaderLinkEnabledInThisRecord(): void
    {
        self::assertTrue($this->create_process->isTCAFieldActiveForThisRecord('tt_content', 'header_link', $this->record));
    }
    /**
     * @test
     */
    public function isImageNotEnabledInThisRecord(): void
    {
        self::assertFalse($this->create_process->isTCAFieldActiveForThisRecord('tt_content', 'image', $this->record));
    }
}
